version: "2"

services:
  app:
    container_name: go-crud
    image: golang
    build: .
    volumes:
      - .:/go/src/go-crud
    working_dir: /go/src/go-crud
    # command: bash -c "GO111MODULE=on go mod vendor && go build && ./go-crud"
    ports:
      - "8000:8000"

  db:
    image: postgres
    ports:
    - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go_crud_dev